Fix “not all arguments converted during string formatting”
A recent `,` was introduced, causing a failure in the logging call:

```
Epoch 1: 100%|████████████████| 760/760 [07:29<00:00,  4.63batch/s, batch_nb=719, loss=0.347, v_nb=1--- Logging error ---                                                                                 
Traceback (most recent call last):
  File "/home/mog/opt/miniconda/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/home/mog/opt/miniconda/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/home/mog/.virtualenvs/mloncode/lib/python3.7/site-packages/coloredlogs/__init__.py", line 1116, in format
    return logging.Formatter.format(self, record)
  File "/home/mog/opt/miniconda/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/home/mog/opt/miniconda/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/mog/.virtualenvs/mloncode/bin/mloncode", line 11, in <module>
    load_entry_point('mloncode', 'console_scripts', 'mloncode')()
  File "/home/mog/work/mloncode/mloncode/__main__.py", line 9, in main
    handler(**kw_args)
  File "/home/mog/work/mloncode/mloncode/pipelines/codrep/train.py", line 212, in train
    trainer.fit(model)
  File "/home/mog/.virtualenvs/mloncode/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 364, in fit
    self.run_pretrain_routine(model)
  File "/home/mog/.virtualenvs/mloncode/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 471, in run_pretrain_routine
    self.train()
  File "/home/mog/.virtualenvs/mloncode/lib/python3.7/site-packages/pytorch_lightning/trainer/train_loop_mixin.py", line 60, in train
    self.run_training_epoch()
  File "/home/mog/.virtualenvs/mloncode/lib/python3.7/site-packages/pytorch_lightning/trainer/train_loop_mixin.py", line 114, in run_training_epoch
    self.run_evaluation(test=self.testing)
  File "/home/mog/.virtualenvs/mloncode/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop_mixin.py", line 160, in run_evaluation
    logs=self.callback_metrics)
  File "/home/mog/.virtualenvs/mloncode/lib/python3.7/site-packages/pytorch_lightning/callbacks/pt_callbacks.py", line 257, in on_epoch_end
    f' saving model to {filepath}')
Message: '\nEpoch 00001: eval_mrr improved from -inf to 0.29670,'
Arguments: (' saving model to out/train/_ckpt_epoch_1.ckpt',)
```
This commit removes this extra comma.