Specify packaging version to be more than 17.0
Older version of packaging causes an error when saving model checkpoint.

The error is in the atomic_save: `if Version(torch.__version__).release[:3] == (1, 6, 0):`

For old version of packaging (e.g., 16.8) the call produce the following errror:

`AttributeError: 'Version' object has no attribute 'release'`