Delete stub forward() method in Module
The current stub breaks TorchScript/`to_torchscript` with:

```
otSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
  File "/opt/conda/envs/image-gen/lib/python3.11/site-packages/pytorch_lightning/core/module.py", line 657
    def forward(self, *args: Any, **kwargs: Any) -> Any:
                                   ~~~~~~~ <--- HERE
        r"""Same as :meth:`torch.nn.Module.forward`.
```

This becomes an issue when you use a module as container for other modules with bespoke methods and do not rely on the default forward call.